# Generated by Django 4.2.11 on 2025-03-24 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recruitment.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_alter_employeeshiftschedule_auto_punch_out_time'),
        ('employee', '0001_initial'),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('schedule_date', models.DateTimeField(blank=True, null=True, verbose_name='Schedule date')),
                ('resume', models.FileField(upload_to='recruitment/resume', validators=[recruitment.models.validate_pdf])),
                ('source', models.CharField(blank=True, choices=[('application', 'Application Form'), ('software', 'Inside software'), ('other', 'Other')], max_length=20, null=True, verbose_name='Source')),
                ('start_onboard', models.BooleanField(default=False, verbose_name='Start Onboard')),
                ('hired', models.BooleanField(default=False, verbose_name='Hired')),
                ('canceled', models.BooleanField(default=False, verbose_name='Canceled')),
                ('converted', models.BooleanField(default=False, verbose_name='Converted')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('sequence', models.IntegerField(default=0, null=True)),
                ('probation_end', models.DateField(editable=False, null=True)),
                ('offer_letter_status', models.CharField(choices=[('not_sent', 'Not Sent'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('joined', 'Joined')], default='not_sent', editable=False, max_length=10)),
                ('last_updated', models.DateField(auto_now=True, null=True)),
                ('converted_employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_get', to='employee.employee', verbose_name='Employee')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('job_position_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.jobposition', verbose_name='Job Position')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('recruitment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidate_application', to='recruitment.recruitment', verbose_name='Recruitment')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_referral', to='employee.employee', verbose_name='Referral')),
                ('stage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recruitment.stage', verbose_name='Stage')),
            ],
            options={
                'ordering': ['sequence'],
                'permissions': (('view_history', 'View Candidate History'), ('archive_candidate', 'Archive Candidate')),
                'unique_together': {('recruitment_id',)},
            },
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='HistoricalCandidate',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='converted',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='converted_employee_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='hired',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='job_position_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='offer_letter_status',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='probation_end',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='recruitment_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='referral',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='schedule_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='sequence',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='source',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='stage_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='start_onboard',
        ),
    ]
