# Generated by Django 4.2.11 on 2025-03-26 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_candidateapplication_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateapplication',
            options={'ordering': ['sequence']},
        ),
    ]
