# Generated by Django 4.2.11 on 2025-03-27 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_alter_candidateapplication_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillzonecandidate',
            old_name='candidate_id',
            new_name='candidate',
        ),
        migrations.AddField(
            model_name='skillzonecandidate',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='skillzone_applications', to='recruitment.candidateapplication', verbose_name='Application'),
        ),
    ]
