# Generated by Django 4.2.11 on 2025-03-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_rename_candidate_id_skillzonecandidate_candidate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='candidate_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate', verbose_name='Candidate'),
        ),
    ]
