# Generated by Django 4.2.11 on 2025-02-25 19:05

import biometric.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevices',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('machine_type', models.CharField(choices=[('zk', 'ZKTeco Biometric'), ('anviz', 'Anviz Biometric'), ('cosec', 'Matrix COSEC Biometric')], max_length=18, null=True)),
                ('machine_ip', models.CharField(blank=True, default='', max_length=15, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('zk_password', models.CharField(blank=True, default='0', max_length=100, null=True)),
                ('cosec_username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('cosec_password', models.CharField(blank=True, max_length=100, null=True)),
                ('anviz_request_id', models.CharField(blank=True, max_length=200, null=True)),
                ('api_url', models.CharField(blank=True, max_length=200, null=True)),
                ('api_key', models.CharField(blank=True, max_length=100, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('api_token', models.CharField(blank=True, max_length=500, null=True)),
                ('api_expires', models.CharField(blank=True, max_length=100, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('is_scheduler', models.BooleanField(default=False)),
                ('scheduler_duration', models.CharField(default='00:00', max_length=10, null=True, validators=[biometric.models.validate_schedule_time_format])),
                ('last_fetch_date', models.DateField(blank=True, null=True)),
                ('last_fetch_time', models.TimeField(blank=True, null=True)),
                ('company_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.company')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Biometric Device',
                'verbose_name_plural': 'Biometric Devices',
            },
        ),
        migrations.CreateModel(
            name='COSECAttendanceArguments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_fetch_roll_ovr_count', models.CharField(max_length=100, null=True)),
                ('last_fetch_seq_number', models.CharField(max_length=100, null=True)),
                ('device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biometric.biometricdevices')),
            ],
        ),
        migrations.CreateModel(
            name='BiometricEmployees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('ref_user_id', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999)])),
                ('user_id', models.CharField(max_length=100)),
                ('device_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biometric.biometricdevices')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Employee in Biometric Device',
                'verbose_name_plural': 'Employees in Biometric Device',
            },
        ),
    ]
